
(function () {
    var takePicture = document.querySelector("#take-picture"),
        showPicture = document.querySelector("#show-picture");
        imageURL = document.querySelector("#imageURL");
    if (takePicture && showPicture) {
        // Set events
        takePicture.onchange = function (event) {
            // Get a reference to the taken picture or chosen file
            var files = event.target.files,
                file;
            if (files && files.length > 0) {
                file = files[0];
                try {
                    // Create ObjectURL
                    var imgURL = window.URL.createObjectURL(file);

                    // Set img src to ObjectURL
                    showPicture.src = imgURL;
                    console.log(imgURL);
                    imageURL.value(imgURL);
                    // Revoke ObjectURL
                    //URL.revokeObjectURL(imgURL);
                    var fs = require('fs');
                    // string generated by canvas.toDataURL()
                    // Grab the extension to resolve any image error
                    var ext = imgURL.split(';')[0].match(/jpeg|png|gif/)[0];
                    // strip off the data: url prefix to get just the base64-encoded bytes
                    var data = imgURL.replace(/^data:image\/\w+;base64,/, "");
                    var buf = new Buffer(data, 'base64');
                    fs.writeFile('image.' + ext, buf);                    


                }
                catch (e) {
                    try {
                        // Fallback if createObjectURL is not supported
                        var fileReader = new FileReader();
                        fileReader.onload = function (event) {
                            showPicture.src = event.target.result;
                        };
                        fileReader.readAsDataURL(file);
                    }
                    catch (e) {
                        //
                        var error = document.querySelector("#error");
                        if (error) {
                            error.innerHTML = "Neither createObjectURL or FileReader are supported";
                        }
                    }
                }
            }
        };
    }
})();